import './js/modalFooterTeam';
import './js/api';
import './js/film-card';
import './js/films-gallery';
import './js/pagination';
import './js/films-gallery-trends';
import './js/library-films-gallery';
import './js/localStorage';
import './js/switch';
