import './js/loaders';
import './js/modalFooterTeam';
import './js/api';
import './js/click-library-btn';
import './js/film-card';
// import './js/pagination';
// import './js/films-gallery-trends';
import './js/library-films-gallery';
import './js/localStorage';
import './js/switch';
import './js/card-info-show-library';
